site_name: ReCoDE Home

theme:
  # recommend leaving this as is
  name: material
  favicon: favicon.png

  language: en

# Static files
  static_templates:
    - 404.html
  
  # change as appropriate

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  # SPA behaviour
  features:
    - navigation.instant
    - navigation.top
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  font:
    text: Roboto
    code: Roboto Mono

  logo: favicon.png

# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ImperialCollegeLondon/ReCoDE-home

extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - include-markdown # https://github.com/mondeja/mkdocs-include-markdown-plugin
  - search
  - tags
  - literate-nav
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  # - pymdownx.highlight:
  #     anchor_linenums: true
  # - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  # - pymdownx.magiclink:
  #     repo_url_shorthand: true
  #     user: squidfunk # change to ReCoDE
  #     repo: mkdocs-material # change to ReCoDE
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

# Page tree
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Exemplars: 
    - exemplars/index.md
    - exemplars/*.md
  - People: people.md
  - Contact: contact.md
  - Licence: licence.md
