site_name: ReCoDE Home
theme:
  # recommend leaving this as is
  name: material
  favicon: favicon.png
  
  # change as appropriate
  palette:
    primary: blue grey
    accent: green

  # SPA behaviour
  features:
    - navigation.instant
    - navigation.top
    - navigation.indexes

plugins:
  - include-markdown # https://github.com/mondeja/mkdocs-include-markdown-plugin
  - search
  - tags
  - literate-nav

markdown_extensions:
  - meta

nav:
  - Exemplars:
    - exemplars/index.md
    - exemplars/*.md
