site_name: ReCoDE Home

theme:
  name: material
  favicon: favicon.png
  logo: favicon.png
  custom_dir: overrides
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  # SPA behaviour
  features:
    - navigation.instant
    - navigation.top
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  # Static files
  static_templates:
    - 404.html

# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ImperialCollegeLondon/ReCoDE-home

extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - include-markdown
  - search
  - tags:
      tags_file: tags.md
  - literate-nav
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - meta
  - toc:
      permalink: true
  - pymdownx.snippets:
      url_download: true
  - pymdownx.tabbed:
      alternate_style: true

# Page tree
nav:
  - Home: index.md
  - About: about.md
  - Getting started: getting-started.md
  - Exemplars: 
    - exemplars/index.md
    - exemplars/*.md
  - Topics: tags.md
  - People: people.md
  - Contact: contact.md
  - Licence: licence.md
